
var map_sprites = {
	"null":						{'r': 	22,	'c':	0,	'o':	false,	'p':    0,	'd':	0},
	"kitchen-sink":				{'r': 	23,	'c':	0,	'o':	true,	'p':    0,	'd':	0},
	"splat-01":					{'r': 	30,	'c':	0,	'o':	false,	'p':    0,	'd':	0},
	"splat-02":					{'r': 	30,	'c':	1,	'o':	false,	'p':    0,	'd':	0},
	"splat-03":					{'r': 	30,	'c':	2,	'o':	false,	'p':    0,	'd':	0},
	"splat-04":					{'r': 	30,	'c':	3,	'o':	false,	'p':    0,	'd':	0},
	"stain-01":					{'r': 	31,	'c':	0,	'o':	false,	'p':    0,	'd':	0},
	"stain-02":					{'r': 	31,	'c':	1,	'o':	false,	'p':    0,	'd':	0},
	"stain-03":					{'r': 	31,	'c':	2,	'o':	false,	'p':    0,	'd':	0},
	"stain-04":					{'r': 	31,	'c':	3,	'o':	false,	'p':    0,	'd':	0}
};

var map_tiles = {
	"null":							{'r': 	0,	'c':	0,	'o':	false,	'p':	0,	'd':	0},
	"block":						{'r': 	0,	'c':	1,	'o':	true,	'p':    0,	'd':	0},
	"clear":						{'r': 	0,	'c':	2,	'o':	false,	'p':    0,	'd':	0},
	"grass-01":						{'r': 	1,	'c':	0,	'o':	false,	'p':    0,	'd':	0},
	"grass-02-t":					{'r': 	1,	'c':	1,	'o':	false,	'p':    0,	'd':	0},
	"grass-02-l":					{'r': 	1,	'c':	2,	'o':	false,	'p':    0,	'd':	0},
	"grass-02-b":					{'r': 	1,	'c':	3,	'o':	false,	'p':    0,	'd':	0},
	"grass-02-r":					{'r': 	1,	'c':	4,	'o':	false,	'p':    0,	'd':	0},
	"grass-03-t":					{'r': 	1,	'c':	5,	'o':	false,	'p':    0,	'd':	0},
	"grass-03-l":					{'r': 	1,	'c':	6,	'o':	false,	'p':    0,	'd':	0},
	"grass-03-b":					{'r': 	1,	'c':	7,	'o':	false,	'p':    0,	'd':	0},
	"grass-03-r":					{'r': 	1,	'c':	8,	'o':	false,	'p':    0,	'd':	0},
	"pavement-01-t":				{'r': 	3,	'c':	0,	'o':	false,	'p':	0,	'd':	0},
	"pavement-01-l":				{'r': 	3,	'c':	1,	'o':	false,	'p':	0,	'd':	0},
	"pavement-01-b":				{'r': 	3,	'c':	2,	'o':	false,	'p':	0,	'd':	0},
	"pavement-01-r":				{'r': 	3,	'c':	3,	'o':	false,	'p':	0,	'd':	0},
	"pavement-02-t":				{'r': 	3,	'c':	4,	'o':	false,	'p':	0,	'd':	0},
	"pavement-02-l":				{'r': 	3,	'c':	5,	'o':	false,	'p':	0,	'd':	0},
	"pavement-02-b": 				{'r': 	3,	'c':	6,	'o':	false,	'p':	0,	'd':	0},
	"pavement-02-r": 				{'r': 	3,	'c':	7,	'o':	false,	'p':	0,	'd':	0},
	"pavement-03-t": 				{'r': 	3,	'c':	8,	'o':	false,	'p':	0,	'd':	0},
	"pavement-03-l": 				{'r': 	3,	'c':	9,	'o':	false,	'p':	0,	'd':	0},
	"pavement-03-b": 				{'r': 	3,	'c':	10,	'o':	false,	'p':	0,	'd':	0},
	"pavement-03-r": 				{'r': 	3,	'c':	11,	'o':	false,	'p':	0,	'd':	0},
	"road-01-t": 					{'r': 	4,	'c':	0,	'o':	false,	'p':	0,	'd':	10},
	"road-01-l": 					{'r': 	4,	'c':	1,	'o':	false,	'p':	0,	'd':	10},
	"road-01-b": 					{'r': 	4,	'c':	2,	'o':	false,	'p':	0,	'd':	10},
	"road-01-r": 					{'r': 	4,	'c':	3,	'o':	false,	'p':	0,	'd':	10},
	"road-02-t": 					{'r': 	4,	'c':	4,	'o':	false,	'p':	0,	'd':	10},
	"road-02-l": 					{'r': 	4,	'c':	5,	'o':	false,	'p':	0,	'd':	10},
	"road-02-b": 					{'r': 	4,	'c':	6,	'o':	false,	'p':	0,	'd':	10},
	"road-02-r": 					{'r': 	4,	'c':	7,	'o':	false,	'p':	0,	'd':	10},
	"road-03-t": 					{'r': 	4,	'c':	8,	'o':	false,	'p':	0,	'd':	10},
	"road-03-l": 					{'r': 	4,	'c':	9,	'o':	false,	'p':	0,	'd':	10},
	"road-03-b": 					{'r': 	4,	'c':	10,	'o':	false,	'p':	0,	'd':	10},
	"road-03-r": 					{'r': 	4,	'c':	11,	'o':	false,	'p':	0,	'd':	10},
	"road-04-t": 					{'r': 	4,	'c':	12,	'o':	false,	'p':	0,	'd':	10},
	"road-04-l": 					{'r': 	4,	'c':	13,	'o':	false,	'p':	0,	'd':	10},
	"road-04-b": 					{'r': 	4,	'c':	14,	'o':	false,	'p':	0,	'd':	10},
	"road-04-r": 					{'r': 	4,	'c':	15,	'o':	false,	'p':	0,	'd':	10},
	"road-05-t": 					{'r': 	4,	'c':	16,	'o':	false,	'p':	0,	'd':	10},
	"road-05-l": 					{'r': 	4,	'c':	17,	'o':	false,	'p':	0,	'd':	10},
	"road-05-b": 					{'r': 	4,	'c':	18,	'o':	false,	'p':	0,	'd':	10},
	"road-05-r": 					{'r': 	4,	'c':	19,	'o':	false,	'p':	0,	'd':	10}
};

var layer01 = [
["block", "block", "block", "block", "pavement-01-l", "road-01-l", "road-01-r", "pavement-01-r", "block", "block", "block", "block", "block", "block", "block", "block" ,"pavement-01-l" ,"road-01-l" ,"road-01-r" ,"pavement-01-r"],
["block", "block", "block", "block", "pavement-02-l", "road-01-l", "road-01-r", "pavement-02-r", "block", "block", "block", "block", "block", "block", "block", "block" ,"pavement-02-l" ,"road-01-l" ,"road-01-r" ,"pavement-02-r"],
["block", "block", "block", "block", "pavement-01-l", "road-01-l", "road-01-r", "pavement-01-r", "block", "block", "block", "block", "block", "block", "block", "block" ,"pavement-01-l" ,"road-01-l" ,"road-01-r" ,"pavement-01-r"],
["pavement-01-t", "pavement-01-t", "pavement-02-t", "pavement-01-t", "pavement-03-t", "road-01-l", "road-01-r", "pavement-03-r", "pavement-02-t", "pavement-01-t", "pavement-01-t", "pavement-02-t", "pavement-01-t", "pavement-01-t", "pavement-02-t", "pavement-01-t" ,"pavement-03-t" ,"road-01-l" ,"road-01-r" ,"pavement-03-r"],
["road-01-t", "road-01-t", "road-01-t", "road-01-t", "road-04-t", "road-01-l", "road-01-r", "road-03-b", "road-01-t", "road-01-t", "road-01-t", "road-01-t", "road-01-t", "road-01-t", "road-01-t", "road-01-t", "road-04-t", "road-01-l", "road-01-r", "road-03-b"],
["road-01-b", "road-01-b", "road-01-b", "road-01-b", "road-03-t", "road-01-l", "road-01-r", "road-04-b", "road-01-b", "road-01-b", "road-01-b", "road-01-b", "road-01-b", "road-01-b", "road-01-b", "road-01-b", "road-03-t", "road-01-l", "road-01-r", "road-04-b"],
["pavement-01-b", "pavement-01-b", "pavement-02-b", "pavement-01-b", "pavement-03-l", "road-01-l", "road-01-r", "pavement-03-b", "pavement-02-b", "pavement-01-b", "pavement-01-b", "pavement-02-b", "pavement-01-b", "pavement-01-b", "pavement-02-b", "pavement-01-b" ,"pavement-03-l" ,"road-01-l" ,"road-01-r" ,"pavement-03-b"],
["block", "block", "block", "block", "pavement-01-l", "road-01-l", "road-01-r", "pavement-01-r", "grass-03-b", "grass-02-b", "grass-02-b", "grass-02-b", "grass-02-b", "grass-02-b", "grass-02-b", "grass-03-l" ,"pavement-01-l" ,"road-01-l" ,"road-01-r" ,"pavement-01-r"],
["block", "block", "block", "block", "pavement-01-l", "road-01-l", "road-01-r", "pavement-01-r", "grass-02-r", "grass-01", "grass-01", "grass-01", "grass-01", "grass-01", "grass-01", "grass-02-l" ,"pavement-01-l" ,"road-01-l" ,"road-01-r" ,"pavement-01-r"],
["block", "block", "block", "block", "pavement-01-l", "road-01-l", "road-01-r", "pavement-01-r", "grass-02-r", "grass-01", "grass-01", "grass-01", "grass-01", "grass-01", "grass-01", "grass-02-l" ,"pavement-01-l" ,"road-01-l" ,"road-01-r" ,"pavement-01-r"],
["block", "block", "block", "block", "pavement-01-l", "road-01-l", "road-01-r", "pavement-01-r", "grass-02-r", "grass-01", "grass-01", "grass-01", "grass-01", "grass-01", "grass-01", "grass-02-l" ,"pavement-01-l" ,"road-01-l" ,"road-01-r" ,"pavement-01-r"],
["block", "block", "block", "block", "pavement-02-l", "road-01-l", "road-01-r", "pavement-02-r", "grass-02-r", "grass-01", "grass-01", "grass-01", "grass-01", "grass-01", "grass-01", "grass-02-l" ,"pavement-02-l" ,"road-01-l" ,"road-01-r" ,"pavement-02-r"],
["block", "block", "block", "block", "pavement-01-l", "road-01-l", "road-01-r", "pavement-01-r", "grass-03-r", "grass-02-t", "grass-02-t", "grass-02-t", "grass-02-t", "grass-02-t", "grass-02-t", "grass-03-t" ,"pavement-01-l" ,"road-01-l" ,"road-01-r" ,"pavement-01-r"],
["pavement-01-t", "pavement-01-t", "pavement-02-t", "pavement-01-t", "pavement-03-t", "road-01-l", "road-01-r", "pavement-03-r", "pavement-02-t", "pavement-01-t", "pavement-01-t", "pavement-02-t", "pavement-01-t", "pavement-01-t", "pavement-02-t", "pavement-01-t" ,"pavement-03-t" ,"road-01-l" ,"road-01-r" ,"pavement-03-r"],
["road-01-t", "road-01-t", "road-01-t", "road-01-t", "road-04-t", "road-01-l", "road-01-r", "road-03-b", "road-01-t", "road-01-t", "road-01-t", "road-01-t", "road-01-t", "road-01-t", "road-01-t", "road-01-t", "road-04-t", "road-01-l", "road-01-r", "road-03-b"],
["road-01-b", "road-01-b", "road-01-b", "road-01-b", "road-03-t", "road-01-l", "road-01-r", "road-04-b", "road-01-b", "road-01-b", "road-01-b", "road-01-b", "road-01-b", "road-01-b", "road-01-b", "road-01-b", "road-03-t", "road-01-l", "road-01-r", "road-04-b"],
["pavement-01-b", "pavement-01-b", "pavement-02-b", "pavement-01-b", "pavement-03-l", "road-01-l", "road-01-r", "pavement-03-b", "pavement-02-b", "pavement-01-b", "pavement-01-b", "pavement-02-b", "pavement-01-b", "pavement-01-b", "pavement-02-b", "pavement-01-b" ,"pavement-03-l" ,"road-01-l" ,"road-01-r" ,"pavement-03-b"],
["block", "block", "block", "block", "pavement-01-l", "road-01-l", "road-01-r", "pavement-01-r", "block", "block", "block", "block", "block", "block", "block", "block" ,"pavement-01-l" ,"road-01-l" ,"road-01-r" ,"pavement-01-r"],
["block", "block", "block", "block", "pavement-01-l", "road-01-l", "road-01-r", "pavement-01-r", "block", "block", "block", "block", "block", "block", "block", "block" ,"pavement-01-l" ,"road-01-l" ,"road-01-r" ,"pavement-01-r"],
["block", "block", "block", "block", "pavement-01-l", "road-01-l", "road-01-r", "pavement-01-r", "block", "block", "block", "block", "block", "block", "block", "block" ,"pavement-01-l" ,"road-01-l" ,"road-01-r" ,"pavement-01-r"]
];

var layer02 = [
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "kitchen-sink", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
["null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"],
];